(* Read a graph from a file,
 * Write a graph to a file. *)

open Graph

type path = string

(* Values are read as strings. *)
val from_file: path -> string graph

(* Similarly, we write only a string graph.
 * If necessary, use gmap (to be written by you) to prepare the input graph. *)
val write_file: path -> string graph -> unit

(* Write the result of Ford-Fulkerson computation on a given graph in a file *)
val write_flow_in_file: int -> path -> unit

(* Write a path (id list) in a file *)
val write_path_in_file: int list option -> path -> unit

(* writes a string graph in dot format *)
val export: path -> string graph -> unit
(* The format of files is compatible with the files generated by:
   https://algorithms.discrete.ma.tum.de/graph-algorithms/flow-ford-fulkerson/index_en.html
*)
